apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-smtp-relay.fullname" . }}
  labels:
    {{- include "web-smtp-relay.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web-smtp-relay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web-smtp-relay.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "web-smtp-relay.fullname" . }}-config