apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-smtp-relay.fullname" . }}-config
  labels:
    {{- include "web-smtp-relay.labels" . | nindent 4 }}
data:
  config.yaml: |
    users:
      {{- range $key, $value := .Values.config.users }}
      {{ $key }}:
        password: {{ $value.password }}
        {{- if $value.smtp }}
        smtp:
          host: {{ $value.smtp.host }}
          port: {{ $value.smtp.port }}
          username: {{ $value.smtp.username }}
          password: {{ $value.smtp.password }}
        {{- end }}
      {{- end }}

    smtp:
      host: {{ .Values.config.smtp.host }}
      port: {{ .Values.config.smtp.port }}
      username: {{ .Values.config.smtp.username }}
      password: {{ .Values.config.smtp.password }}

    port: {{ .Values.config.port }}